export EDITOR=nvim
export N_PREFIX=~/.n
export PATH="$HOME/bin:$HOME/.n/bin:$PATH"
export GOROOT=$HOME/opt/go
export GOPATH=$PATH:$GOROOT/bin
export LEIN_USE_BOOTCLASSPATH=no
export DOTDROP_PROFILE="home"
