config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_coc-settings.json:
    src: config/nvim/coc-settings.json
    dst: ~/.config/nvim/coc-settings.json
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_plugins.vim:
    src: config/nvim/plugins.vim
    dst: ~/.config/nvim/plugins.vim
  f_plug.vim:
    src: config/nvim/autoload/plug.vim
    dst: ~/.config/nvim/autoload/plug.vim
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
  d_i3:
    src: config/regolith/i3
    dst: ~/.config/regolith/i3
  d_i3xrocks:
    src: config/regolith/i3xrocks
    dst: ~/.config/regolith/i3xrocks
variables:
  git_email: amir@eldor.dev
profiles:
  home:
    dotfiles:
    - f_zshrc
    - f_gitconfig
    - f_gitignore
    - f_coc-settings.json
    - f_init.vim
    - f_plugins.vim
    - f_plug.vim
    - f_zshenv
    - f_bash_aliases
    - d_i3
    - d_i3xrocks
  zencity:
    variables:
      git_email: amire@zencity.io
    include:
    - home
